# Generated by Django 2.1.5 on 2019-01-24 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=' ')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('favorite', models.PositiveIntegerField(default=0)),
                ('duration_from', models.PositiveIntegerField(blank=True, default=0)),
                ('duration_to', models.PositiveIntegerField(blank=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='hobbies.Ingredient')),
                ('sub_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_id', to='hobbies.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='subingredients',
            unique_together={('parent_ingredient', 'sub_ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together={('recipe', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('recipe', 'order')},
        ),
    ]
