# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_subingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredientref',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredientref',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='subingredient',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='subingredient',
            old_name='sub_id',
            new_name='sub',
        ),
    ]
