# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_auto_20181108_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredientRef',
            new_name='RecipeIngredients',
        ),
        migrations.RenameModel(
            old_name='SubIngredient',
            new_name='SubIngredients',
        ),
    ]
