# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0006_auto_20181108_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='quantity',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
