# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0007_recipeingredients_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='quantity',
        ),
    ]
