# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0008_remove_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='quantity',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
