# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0009_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
