# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0010_auto_20181108_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together=set([('recipe', 'ingredient', 'description')]),
        ),
    ]
