# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0012_auto_20181109_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subingredients',
            unique_together=set([('parent_ingredient', 'sub_ingredient')]),
        ),
    ]
