# Generated by Django 2.1.3 on 2018-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0014_auto_20181109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration_from',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration_to',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=3),
        ),
    ]
