# Generated by Django 2.1.4 on 2019-01-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0014_auto_20181109_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration_from',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration_to',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hobbies.FoodCategory'),
        ),
    ]
