# Generated by Django 2.1.3 on 2018-12-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0015_auto_20181226_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hobbies.FoodCategory'),
        ),
    ]
