# Generated by Django 2.1.3 on 2018-12-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0016_auto_20181230_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food_category',
        ),
    ]
