# Generated by Django 2.1.3 on 2018-12-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0017_remove_recipe_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='date_modified',
        ),
    ]
