# Generated by Django 2.1.3 on 2018-12-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0018_auto_20181230_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
