# Generated by Django 2.1.3 on 2018-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0019_delete_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
