# Generated by Django 2.1.3 on 2018-12-30 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0020_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
