# Generated by Django 2.1.3 on 2018-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0021_auto_20181230_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration_from',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration_to',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=100),
        ),
    ]
