# Generated by Django 2.1.3 on 2018-12-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0022_auto_20181230_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='date_modified',
        ),
    ]
