# Generated by Django 2.1.3 on 2018-12-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0023_auto_20181230_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hobbies.FoodCategory'),
        ),
    ]
