# Generated by Django 2.1.4 on 2019-01-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0015_auto_20190104_1601'),
        ('hobbies', '0024_recipe_food_category'),
    ]

    operations = [
    ]
