# Generated by Django 2.1.5 on 2019-01-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0025_merge_20190106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration_from',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration_to',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.FoodCategory'),
        ),
    ]
